### ISSUE TITLE
Additional Collaborators

### ISSUE THREAD

**Issue by BMartinos** [openhie/instant#5]
Hi All

Just want to find out if there is a specific process to follow before adding anyone as a collaborator to this project. Should we manage this under Teams, or rather individually added?

Regards,

**Comment by citizenrich** [comment]
I’m not experienced enough to comment, happy for suggestions.

**Comment by BMartinos** [comment]
Thanks @citizenrich. 

I think its a bit cleaner to manage users via teams but this requires a bit of setup on the openhie organisation which might be a bit tricky. For now ive just added two of my team members as Collaborators to start contributing to the repo.
