### ISSUE TITLE
Authentication issues after docker-compose install

### ISSUE THREAD

**Issue by mrjones-plip** [openhie/instant#78]
Hi there! We're working to set up Instant OpenHIE by following the [Docker Compose steps per your docs](https://github.com/openhie/instant#docker-compose).  We're testing on an EC2 instance running Ubuntu 18.

This initially worked and we were able to create patient records with API via OpenHIM to FHIR using our test call: `curl -sv -H "Content-Type: application/json" -d '{"resourceType":"Patient","gender":"female"}' http://URL-OF-INSTANCE:5001/fhir/Patient`.   This would be accompanied by success messages when we looked at the OpenHIM container (`docker logs openhim-core --follow`) with entries like `Client (Test Client) is Authenticated.` and `The request, '/fhir/Patient' is authorised to access FHIR Server`

After some time, and through no changes that we know of, this call no longer works because of an authentication issues.  Now when we look in the OpenHIM container and make our `curl` call (which unsurprisingly returns `401 Unauthorized` ), we see these:

```
2021-03-23T21:58:58.370Z [worker1] info: No basic auth details supplied, trying next auth mechanism if any...
2021-03-23T21:58:58.371Z [worker1] info: Could NOT authenticate via TLS: undefined, trying next auth mechanism if any...
2021-03-23T21:58:58.384Z [worker1] info: No channel matched the request /fhir/Patient
2021-03-23T21:58:58.385Z [worker1] info: The request, '/fhir/Patient', is not authorised to access any channels.
```

This is actually the second time this happened. The the first time we rebuilt the system (`yarn docker:instant destroy -t docker` etc.) which solved the problem, but it came back again.  We'd like to use the existing  broken state to troubleshoot what happened to fix for the long term.  Can you advice next steps we should take?  

Much thanks!

**Comment by mariusnaude** [comment]
Hi @mrjones-plip , we are currently investigating this issue. Is it possible to provide the Authentication details you are using with the Client call ?

**Comment by mrjones-plip** [comment]
@mariusnaude - The instance we were testing with has long since been rebuilt.  Our "fix" was to just not use the docker config in this repo, and [use another one copied from it](https://github.com/medic/chis-interoperability/).

I'm not at all sure, but my suspicion was that the [ephemeral container's call](https://github.com/openhie/instant/blob/master/core/docker/importer/docker-compose.config.yml#L21) to node to pass in [the config](https://github.com/openhie/instant/blob/master/core/docker/importer/volume/openhim-import.json) was being called again some how and this was possibly resetting the password?

Possibly more work than it was worth, but our work around was to just use a one liner `curl` call in our [modified compose bash script](https://github.com/medic/chis-interoperability/blob/master/docker/compose.sh#L36).

Feel free to close this ticket if this ends up all not being helpful!  Otherwise, I'd be happy to help merge any of our changes upstream to this repo if that's helpful.

**Comment by bradsawadye** [comment]
Hi @mrjones-plip, I am currently looking into this issue. This is something that we've never experienced. It's good that you found a workaround, but I don't see how the ephemeral container for configuring the OpenHIM can reset the password because once the password has been set, the ephemeral container [core-config-importer](https://github.com/openhie/instant/blob/master/core/docker/importer/docker-compose.config.yml#L6) will not be able to access the OpenHIM as it uses the [default password](https://github.com/openhie/instant/blob/master/core/docker/importer/docker-compose.config.yml#L13) which would have changed would have been changed to `instant101`. 

From the logs, you sent in your first message I see that even the channel had been removed which makes me suspect this could have been a mongo DB issue.

I'm struggling to replicate your issue. If you can please provide us with more details about the EC2 instance you were on when you experienced the issue.

**Comment by mrjones-plip** [comment]
@bradsawadye  - thanks so much for looking into this!  I agree an issue with Mongo does sound the more likely cause given, as you said, the password would be changed and even if the ephemeral container re-ran, it couldn't log in to re-update the config.

That said, I suspect there's not much we can do to reproduce the issue as our EC2 instance has both been rebuilt using our [own flavor OpenHIE docker-compose](https://github.com/medic/chis-interoperability/) files and has been stable for months. 

My main interest with this ticket was helping the larger Instant OpenHIE be stable and have accurate docs.  Hopefully [Matt's recent updates](https://github.com/openhie/instant/pull/104) fixes other issues, including this one?  If following [your docker steps](https://github.com/openhie/instant/tree/master/core/docker) results in stable build, we're all good!

Feel free to close this if y'all feel there's nothing actionable.
