### ISSUE TITLE
Windows: CLI error on docker path

### ISSUE THREAD

**Issue by citizenrich** [openhie/instant#87]
CLI docker commands fail with an error.

![Screenshot 2021-05-04 081630](https://user-images.githubusercontent.com/2528387/117002284-5dee0180-acb1-11eb-8b1f-989904e5640a.png)

**Comment by michaelloosen** [comment]
@citizenrich This should no longer be the case, please update if you are still facing issues here?

**Comment by citizenrich** [comment]
Thanks @michaelloosen I'll have access to a Windows PC on Friday and can check. Thanks!

**Comment by citizenrich** [comment]
I've had a look at the CLI on Windows. I built it both on Windows and on macOS and transfered it over to test. When running any CLI up/down command for any package, it errors with:
```
          > core/docker/compose.sh: line 2: $'\r': command not found
         > core/docker/compose.sh: line 4: $'\r': command not found
         > core/docker/compose.sh: line 29: syntax error near unexpected token `elif'
'        > core/docker/compose.sh: line 29: `elif [ "$1" == "up" ]; then
```

This is an odd error, as it suggests that there are Windows CRLF endings instead of *Nix endings (LF). I will look a bit more into it this week.

**Comment by citizenrich** [comment]
Closing as stale.
